name: tic-tac cicd
on:
  push:
    branches: [main]
    paths-ignore: 
      - 'kubernetes/*'
  pull_request: 
    branches: 
      - main
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: nodejs setup
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: install dependencies
        run: npm ci

      - name: build
        run: npm run build
      
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tic-tac-artifact
          path: dist/
          retention-days: 7

      